frameworkVersion: "3"

service: serverless
plugins:
  - "@yandex-cloud/serverless-plugin"

provider:
  name: yandex-cloud
  runtime: nodejs22
  httpApi:
    payload: "1.0"

package:
  patterns:
    - "!**"
    - package.json
    - package-lock.json
    - dist/**/*.js

functions:
  cryptoBot:
    handler: dist/index.cryptoBotHandler
    memorySize: 128
    timeout: 15
